basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket, name='basket'),
    path('add_product/<str:product_id>', views.add_product, name='add_product'),
    path('subtract_product/<str:product_id>', views.subtract_product, name='subtract_product'),
    path('order', views.order, name='order'),
    path('create_order', views.create_order, name='create_order'),
]

catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    # path('product/<int:pk>', views.ProductView.as_view(), name='product'),
    path('product/<int:product_id>', views.product, name='product'),
]

onlineStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('registration.urls')),
    path('', include('catalogue.urls')),
    path('basket/', include('basket.urls')),
    path('profile/', include('userProfile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userProfile/urls.py
from django.urls import path

from . import views

app_name = 'userProfile'
urlpatterns = [
    path('', views.user_profile, name='userProfile'),
    path('new_product', views.new_product, name='new_product'),
    path('product_created', views.product_created, name='product_created'),
    path('change_product', views.change_product, name='change_product'),
    path('delete_product/<int:product_id>', views.del_product, name='del_product'),
    path('modify_product/<int:product_id>', views.modify_product, name='modify_product'),
    path('product_modified/<int:product_id>', views.product_modified, name='product_modified'),
    path('change_status', views.change_status, name='change_status'),
    path('change_order_status_paid/<int:order_id>', views.change_order_status_paid, name='change_order_status_paid'),
    path('change_order_status_unpaid/<int:order_id>', views.change_order_status_unpaid,
         name='change_order_status_unpaid'),
]

basket/models.py
from django.db import models

from catalogue.models import Product
from registration.models import Customer, Adm


class Order(models.Model):
    ord_status = models.CharField(max_length=1, default='1')
    cr_date = models.DateTimeField()
    pay_date = models.DateTimeField(blank=True, null=True, default=None)
    full_pr = models.PositiveSmallIntegerField()
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    seller = models.ForeignKey(Adm, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class Prod_list(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    pr_amount = models.PositiveSmallIntegerField()

userProfile/models.py
from django.db import models

# Create your models here.

userProfile/forms.py
from django import forms

from catalogue.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['pr_name', 'desc', 'ingreds', 'img', 'pr_cost', 'pr_price', 'pr_left']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['pr_name'].label = 'Название'
        self.fields['desc'].label = 'Описание'
        self.fields['ingreds'].label = 'Состав'
        self.fields['img'].label = 'Изображение'
        self.fields['pr_cost'].label = 'Затраты'
        self.fields['pr_price'].label = 'Цена'
        self.fields['pr_left'].label = 'Количество на складе'

        self.fields['desc'].widget.attrs.update(rows=3, maxlength=1000)
        self.fields['ingreds'].widget.attrs.update(rows=3, maxlength=1000)

        self.fields['pr_name'].widget.attrs.update(onChange="correct_field('id_pr_name')")
        self.fields['desc'].widget.attrs.update(onChange="correct_field('id_desc')")
        self.fields['ingreds'].widget.attrs.update(onChange="correct_field('id_ingreds')")

userProfile/views.py
import datetime

from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from basket.models import Order, Prod_list
from catalogue.models import Product
from userProfile.forms import ProductForm


def user_profile(request):
    # если пользователь авторизован
    if request.user.is_authenticated:

        # если авторизован продавец, владелец или системный администратор
        if hasattr(request.user, 'adm'):

            # если авторизован продавец
            if request.user.adm.u_role == '1':
                return render(request, 'userProfile/profile_seller.html', {'date': datetime.date.today()})

            # если авторизован владелец
            elif request.user.adm.u_role == '2':

                # расчет прибыли
                if 'first_date_profit' in request.POST:
                    start_date_profit = request.POST['first_date_profit']
                    end_date_profit = request.POST['last_date_profit']
                    paid_orders = Order.objects.filter(pay_date__range=(start_date_profit, end_date_profit),
                                                       ord_status='2')
                else:
                    paid_orders = Order.objects.filter(ord_status='2')

                profit = 0
                costs = 0
                for paid_order in paid_orders:
                    for prod in paid_order.prod_list_set.all():
                        costs += prod.product.pr_cost * prod.pr_amount
                    profit += paid_order.full_pr
                profit -= costs

                # расчет рейтинга
                products_rating = {}
                for product in Product.objects.all():
                    if 'first_date_rating' in request.POST:
                        start_date_rating = request.POST['first_date_rating']
                        end_date_rating = request.POST['last_date_rating']
                        total_pr_amount = Prod_list.objects.filter(
                            order__ord_status='2',
                            product_id=product.id,
                            order__pay_date__range=(start_date_rating, end_date_rating))
                    else:
                        total_pr_amount = Prod_list.objects.filter(order__ord_status='2', product_id=product.id)

                    if total_pr_amount.count() != 0:
                        total_pr_amount = total_pr_amount.aggregate(total=Sum('pr_amount'))['total']
                        product_profit = (product.pr_price - product.pr_cost) * total_pr_amount
                        products_rating[product.id] = product_profit

                products_rating = sorted(products_rating.items(), key=lambda x: x[1], reverse=True)
                products_rating = dict(products_rating[0:3])

                top_products = []
                for pr in products_rating:
                    top_products.append(Product.objects.get(pk=pr))

                context = {
                    'date': datetime.date.today(),
                    'profit': profit,
                    'products_rating': products_rating,
                    'top_products': top_products,
                }
                if 'first_date_profit' in request.POST:
                    context['start_date_profit'] = request.POST['first_date_profit']
                    context['end_date_profit'] = request.POST['last_date_profit']
                elif 'first_date_rating' in request.POST:
                    context['start_date_rating'] = request.POST['first_date_rating']
                    context['end_date_rating'] = request.POST['last_date_rating']

                return render(request, 'userProfile/profile_owner.html', context)

            # если авторизован системный администратор
            else:
                return render(request, 'userProfile/profile_admin.html', {'date': datetime.date.today()})

        # если авторизован покупатель
        orders = None
        overall_cost = 0
        search_failed = False

        if 'first_date' in request.POST:
            start_date = request.POST['first_date']
            end_date = request.POST['last_date']
            orders = Order.objects.filter(cr_date__range=(start_date, end_date), customer_id=request.user.customer.id)
            if orders.count() == 0:
                search_failed = True
        else:
            orders = Order.objects.filter(customer_id=request.user.customer.id)

        for order in orders:
            overall_cost += order.full_pr

        context = {
            'orders': orders,
            'date': datetime.date.today(),
            'overall_cost': overall_cost,
            'search_failed': search_failed,
        }

        if 'first_date' in request.POST:
            context['start_date'] = request.POST['first_date']
            context['end_date'] = request.POST['last_date']

        return render(request, 'userProfile/profile_customer.html', context)

    else:

        return render(request, 'userProfile/profile_denied.html')


def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('userProfile:product_created'))
    else:
        form = ProductForm()

    return render(request, 'userProfile/new_product.html', {'form': form})


def product_created(request):
    last_product = Product.objects.last()

    context = {
        'new_product': last_product,
    }

    return render(request, 'userProfile/product_created.html', context)


def change_product(request):
    products_list = Product.objects.all()

    context = {
        'products_list': products_list,
    }

    return render(request, 'userProfile/change_product.html', context)


def del_product(request, product_id):
    Product.objects.get(pk=product_id).delete()
    return HttpResponseRedirect(reverse('userProfile:change_product'))


def modify_product(request, product_id):
    product = Product.objects.get(pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()
            return redirect('userProfile:product_modified', product.id)
    else:
        form = ProductForm(instance=product)

    context = {
        'form': form,
        'product': product
    }

    return render(request, 'userProfile/modify_product.html', context)


def product_modified(request, product_id):
    modified_product = Product.objects.get(pk=product_id)

    context = {
        'product': modified_product,
    }

    return render(request, 'userProfile/product_modified.html', context)


def change_status(request):
    unpaid_orders = Order.objects.filter(seller_id=request.user.adm.id, ord_status='1')
    paid_orders = Order.objects.filter(seller_id=request.user.adm.id, ord_status='2')

    context = {
        'unpaid_orders': unpaid_orders,
        # 'paid_orders': paid_orders,
    }

    return render(request, 'userProfile/change_status.html', context)


def change_order_status_paid(request, order_id):
    order = Order.objects.get(pk=order_id)
    order.ord_status = '2'
    order.pay_date = datetime.datetime.now()
    order.save()

    return HttpResponseRedirect(reverse('userProfile:change_status'))


def change_order_status_unpaid(request, order_id):
    order = Order.objects.get(pk=order_id)
    order.ord_status = '1'
    order.pay_date = None
    order.save()

    return HttpResponseRedirect(reverse('userProfile:change_status'))

userProfile/templates/userProfile/change_product.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Изменить/удалить товар</title>

	<link rel="stylesheet" href="{% static 'catalogue/style.css' %}">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>
    <h1 class="headline" style="margin-left: 100px">Список товаров</h1>
        <div class="flex column" style="margin-left: 100px; margin-top: 20px; gap: 20px;">
            {% if products_list %}
                {% for product in products_list %}
                    <div class="product flex" style="width: 55%">
                        <a href="{% url 'catalogue:product' product.id %}">
                            {% if product.img %}
                            <img style="width: 200px;" src="{{ product.img.url }}" alt="" class="pr_img">
                            {% endif %}
                        </a>
                        <div class="product_info">
                            <p class="pr_price title">{{ product.pr_name }}</p>
                            <a href="{% url 'catalogue:product' product.id %}">
                                <p class="pr_name subtitle">{{ product.pr_price }} P</p>
                            </a>
                            <div>
                                <a href="{% url 'userProfile:modify_product' product.id %}">
                                    <button style="margin: 10px 0; background-color: #ffb229" class="primary_button">Изменить товар</button>
                                </a> <br>
                                <button class="primary_button" onclick="confirm_delete({{ product.id }})">Удалить товар</button>
                            </div>
                        </div>
                     </div>
                {% endfor %}
        </div>
            {% else %}
                <p>В базе данных нет ни одного продукта</p>
            {% endif %}

    <script>
        function confirm_delete(pr_id) {
            if (confirm('Вы уверены, что хотите удалить продукт из базы данных?')) {
                document.location.href = `/profile/delete_product/${pr_id}`
                alert('Продукт был удален.')
            }
        }
    </script>
</body>
</html>

userProfile/templates/userProfile/modify_product.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Изменить товар</title>
    <link rel="stylesheet" href="{% static 'catalogue/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>

    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>

    <div style="margin: 40px 0 0 60px">
        <h1 class="title">Изменить товар</h1>
        <div class="flex">
            {% if product.img %}
            <img style="width: 30%; height: auto; margin-right: 10px" src="{{ product.img.url }}" alt="" class="pr_img">
            {% endif %}
            <form action="{% url 'userProfile:modify_product' product.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div>
                        {% language 'ru' %}
                            {{ field.errors }}
                            {{ field.label }}<br> {{ field }}
                        {% endlanguage %}
                    </div>
                {% endfor %}
            <input type="submit" value="Изменить товар" class="primary_button" style="margin-top: 5px">
        </form>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'userProfile/script.js' %}"></script>
</body>
</html>

userProfile/templates/userProfile/new_product.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Добавить товар</title>
    <link rel="stylesheet" href="{% static 'catalogue/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>

    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>

    <div style="margin: 40px 0 0 60px">
        <h1 class="title">Новый товар</h1>
        <form action="{% url 'userProfile:new_product' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

{#        форма через html#}
{#            <label for="prd_name">Название</label><br>#}
{#            <input type="text" maxlength="50" name="prd_name" id="prd_name" required onchange = "correct_field('prd_name')"><br>#}
{#            <label for="prd_desc">Описание</label><br>#}
{#            <textarea cols="50" maxlength="1000" name="prd_desc" id="prd_desc" onchange = "correct_field('prd_desc')"></textarea><br>#}
{#            <label for="prd_ingreds">Состав</label><br>#}
{#            <textarea cols="50" maxlength="1000" name="prd_ingreds" id="prd_ingreds" required onchange = "correct_field('prd_ingreds')"></textarea><br>#}
{#            <label for="prd_img">Изображение</label>#}
{#            <input type="file" accept="image/jpeg" name="prd_img" id="prd_img"><br>#}
{#            <label for="prd_cost">Затраты</label><br>#}
{#            <input type="number" name="prd_cost" id="prd_cost" required><br>#}
{#            <label for="prd_price">Цена</label><br>#}
{#            <input type="number" name="prd_price" id="prd_price" required><br>#}
{#            <label for="prd_left">Количество на складе</label><br>#}
{#            <input type="number" name="prd_left" id="prd_left" required><br>#}
{#            <input type="submit" value="Добавить товар" class="primary_button" style="margin-top: 5px">#}

{#        форма через класс django#}
            {% for field in form %}
                <div>
                    {% language 'ru' %}
                        {{ field.errors }}
                        {{ field.label }}<br> {{ field }}
                    {% endlanguage %}
                </div>
            {% endfor %}
            <input type="submit" value="Добавить товар" class="primary_button" style="margin-top: 5px">
        </form>
    </div>

    <script type="text/javascript" src="{% static 'userProfile/script.js' %}"></script>
</body>
</html>

userProfile/templates/userProfile/product_created.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Товар добавлен</title>
    <link rel="stylesheet" href="{% static 'catalogue/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>

    <div style="margin: 40px 0 0 60px">
        <h1 class="title">Товар добавлен</h1>
        <div class="flex">
            {% if product.img %}
            <img src="{{ new_product.img.url }}" alt="" style="width: 20%">
            {% endif %}
            <div style="margin-left: 10px;">
                <p class="subtitle">Название: {{ new_product.pr_name }}</p>
                <p>Описание: {{ new_product.desc }}</p>
                <p>Состав: {{ new_product.ingreds }}</p>
                <p>Затраты: {{ new_product.pr_cost }} Руб.</p>
                <p>Цена: {{ new_product.pr_price }} Руб.</p>
                <p>Количество на складе: {{ new_product.pr_left }} Шт.</p>
                <a href="{% url 'userProfile:new_product' %}"><button style="margin-top: 10px" class="primary_button">Добавить ещё один товар</button></a>
            </div>
        </div>
    </div>
</body>
</html>

userProfile/templates/userProfile/product_modified.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Товар изменён</title>
    <link rel="stylesheet" href="{% static 'catalogue/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>

    <div style="margin: 40px 0 0 60px">
        <h1 class="title">Товар изменён</h1>
        <div class="flex">
            {% if product.img %}
                <img src="{{ product.img.url }}" alt="" style="width: 20%">
            {% endif %}
            <div style="margin-left: 10px;">
                <p class="subtitle">Название: {{ product.pr_name }}</p>
                <p>Описание: {{ product.desc }}</p>
                <p>Состав: {{ product.ingreds }}</p>
                <p>Затраты: {{ product.pr_cost }} Руб.</p>
                <p>Цена: {{ product.pr_price }} Руб.</p>
                <p>Количество на складе: {{ product.pr_left }} Шт.</p>
                <a href="{% url 'userProfile:modify_product' product.id %}"><button style="margin: 10px 4px 0 0" class="primary_button">Изменить этот товар</button></a>
                <a href="{% url 'userProfile:change_product' %}"><button style="background-color: #ffb229" class="primary_button">Изменить другой товар</button></a>
            </div>
        </div>
    </div>
</body>
</html>

userProfile/templates/userProfile/profile_admin.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Личный кабинет</title>
    <link rel="stylesheet" href="{% static 'catalogue/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>
    <div style="margin-left: 40px">
        <h1 class="headline">Личный кабинет</h1>
        <p class="title">Данные ситемного администратора</p>
        <p>Имя: {{ user.first_name }}</p>
        <p>Фамилия: {{ user.last_name }}</p>
        <p>Почта: {{ user.email }}</p>
        <a href="{% url 'logout' %}" style="text-decoration: underline">Выйти</a> <br>
        {% language 'ru' %}
            <p style="margin: 4px 0 16px">Сегодня {{ date }}</p>
        {% endlanguage %}
        <a href="/admin" style="text-decoration: underline">Администрирование</a>
    </div>
</body>
</html>

userProfile/templates/userProfile/profile_customer.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Личный кабинет</title>
    <link rel="stylesheet" href="{% static 'catalogue/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>
    <div style="margin-left: 40px">
        <h1 class="headline">Личный кабинет</h1>
            <div class="flex">
                <div style="width: 37%">
                    <p class="title">Заказы</p>
                    {% if orders %}
                        {% for order in orders %}
                            <div class="order">
                            <p class="subtitle">Номер {{ order.id }}</p>
                            <span>Состав заказа: </span>
                            {% for pr_list in order.prod_list_set.all %}
                                <span>{{ pr_list.product }} {{ pr_list.pr_amount }}шт. </span>
                            {% endfor %}
{#                            {% for pr_list in order.prod_list_set.all %}#}
{#                                <div class="product flex" style="width: 55%">#}
{#                                    <a href="{% url 'catalogue:product' pr_list.product.id %}">#}
{#                                        <img src="{{ pr_list.product.img.url }}" alt="" class="pr_img">#}
{#                                    </a>#}
{#                                    <div class="product_info">#}
{#                                        <p class="pr_price title">{{ pr_list.product.pr_price }} P</p>#}
{#                                        <a href="{% url 'catalogue:product' pr_list.product.id %}">#}
{#                                            <p class="pr_name subtitle">{{ pr_list.product.pr_name }}</p>#}
{#                                        </a>#}
{#                                        <p class="subtitle" style="font-weight: 700">{{ pr_list.pr_amount }} шт.</p>#}
{#                                    </div>#}
{#                                 </div>#}
{#                            {% endfor %}#}
                            {% language 'ru' %}
                                <p>Дата оформления: {{ order.cr_date }}</p>
                            {% endlanguage %}
                            {% if order.pay_date %}
                                {% language 'ru' %}
                                    <p>Дата оплаты: {{ order.pay_date }}</p>
                                {% endlanguage %}
                            {% endif %}
                            <p>Стоимость: {{ order.full_pr }} P</p>
                            </div>
                        {% endfor %}
                        <p class="subtitle" style="margin: 8px 0">Стоимость покупок: {{ overall_cost }} руб.</p>
                    {% elif search_failed %}
                        <p class="subtitle">Заказов в выбранные даты не найдено</p>
                    {% else %}
                        <p class="subtitle">Вы пока не сделали ни одного заказа</p>
                    {% endif %}
                </div>
                {% if orders or search_failed %}
                <div style="width: 27%;">
                    <p class="title">Фильтр по дате</p>
                    {% language 'ru' %}
                        <p style="margin: 4px 0 16px">Сегодня {{ date }}</p>
                    {% endlanguage %}
                    <p style="margin-bottom: 8px">Искать заказы</p>
                    <form action="{% url 'userProfile:userProfile' %}" method="post">
                        {% csrf_token %}
                        <label for="first_date">C</label>
                        <input type="date" id="first_date" value="{{ start_date }}" name="first_date" size="20" required>
                        <label for="last_date">по</label>
                        <input type="date" id="last_date" value="{{ end_date }}" name="last_date" size="20" required>
                        <input type="submit" value="Найти заказы" class="primary_button">
                    </form>
                </div>
                {% endif %}
                <div style="width: 33%">
                    <p class="title">Данные покупателя</p>
                    <p>Имя: {{ user.first_name }}</p>
                    <p>Фамилия: {{ user.last_name }}</p>
                    <p>Почта: {{ user.email }}</p>
                    <p>Телефон: {{ user.customer.phone }}</p>
                    <p>Адрес: {{ user.customer.district }} район, улица {{ user.customer.street }}, дом {{ user.customer.house }},
                        корпус {{ user.customer.corp }}, кв.{{ user.customer.flat }}, {{ user.customer.p_index }} </p>
                    <a href="{% url 'logout' %}" style="text-decoration: underline">Выйти</a>
                </div>
            </div>

    </div>
</body>
</html>