basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket, name='basket'),
    path('add_product/<str:product_id>', views.add_product, name='add_product'),
    path('subtract_product/<str:product_id>', views.subtract_product, name='subtract_product'),
    path('order', views.order, name='order'),
    path('create_order', views.create_order, name='create_order'),
]

catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    # path('product/<int:pk>', views.ProductView.as_view(), name='product'),
    path('product/<int:product_id>', views.product, name='product'),
]

onlineStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('registration.urls')),
    path('', include('catalogue.urls')),
    path('basket/', include('basket.urls')),
    path('profile/', include('userProfile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userProfile/urls.py
from django.urls import path

from . import views

app_name = 'userProfile'
urlpatterns = [
    path('', views.user_profile, name='userProfile'),
    path('new_product', views.new_product, name='new_product'),
    path('product_created', views.product_created, name='product_created'),
    path('change_product', views.change_product, name='change_product'),
    path('delete_product/<int:product_id>', views.del_product, name='del_product'),
    path('modify_product/<int:product_id>', views.modify_product, name='modify_product'),
    path('product_modified/<int:product_id>', views.product_modified, name='product_modified'),
    path('change_status', views.change_status, name='change_status'),
    path('change_order_status_paid/<int:order_id>', views.change_order_status_paid, name='change_order_status_paid'),
    path('change_order_status_unpaid/<int:order_id>', views.change_order_status_unpaid,
         name='change_order_status_unpaid'),
]

basket/models.py
from django.db import models

from catalogue.models import Product
from registration.models import Customer, Adm


class Order(models.Model):
    ord_status = models.CharField(max_length=1, default='1')
    cr_date = models.DateTimeField()
    pay_date = models.DateTimeField(blank=True, null=True, default=None)
    full_pr = models.PositiveSmallIntegerField()
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    seller = models.ForeignKey(Adm, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class Prod_list(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    pr_amount = models.PositiveSmallIntegerField()

basket/views.py
import datetime

from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from basket.models import Order
from catalogue.models import Product
from registration.models import Adm, Customer


def basket(request):
    product_list = []
    items = {}
    prices = {}
    for i in request.session.keys():
        try:
            items[int(i)] = request.session[i]
        except ValueError:
            continue
    for key in items.keys():
        product_list.append(Product.objects.get(pk=str(key)))
    for product in product_list:
        prices[product.id] = product.pr_price * items[product.id]
    context = {
        'product_list': product_list,
        'product_items': items,
        'product_prices': prices
    }
    return render(request, 'basket/basket.html', context)


def add_product(request, product_id):
    if product_id in request.session:
        request.session[product_id] += 1
    else:
        request.session[product_id] = 1
    # print(request.session.items())
    return HttpResponse()


def subtract_product(request, product_id):
    request.session[product_id] -= 1
    if request.session[product_id] == 0:
        del request.session[product_id]
    # print(request.session.items())
    return HttpResponse()


def order(request):
    return render(request, 'basket/order.html', )


def create_order(request):
    products = {}
    full_price = 0
    user_order = None

    for i in request.session.keys():
        try:
            products[int(i)] = request.session[i]
        except ValueError:
            continue

    if products == {}:
        return HttpResponse("Добавьте товары и оформите заказ")

    for product in products:
        full_price += Product.objects.get(pk=product).pr_price * products[product]

    current_seller = Adm.objects.get(pk=1)
    if request.user.is_authenticated:
        current_user = request.user.customer
        user_order = Order(cr_date=datetime.datetime.now(), full_pr=full_price, customer=current_user,
                           seller=current_seller)
    else:
        temp_login = 'temp' + str(datetime.datetime.now().timestamp())
        user_data = [request.POST['login'], request.POST['last_name'], request.POST['first_name']]
        customer_data = [request.POST['phone'], request.POST['district'], request.POST['street'], request.POST['house'],
                         request.POST['corp'], request.POST['flat'], request.POST['p_index']]

        temp_user = User.objects.create_user(username=temp_login, password=temp_login,
                                             email=user_data[0], first_name=user_data[2], last_name=user_data[1])
        temp_user.save()
        temp_customer = Customer(temp_user.id, temp_user.id, customer_data[0], customer_data[1], customer_data[2],
                                 customer_data[3], customer_data[4], customer_data[5], customer_data[6])
        temp_customer.save()
        user_order = Order(cr_date=datetime.datetime.now(), full_pr=full_price, customer=temp_customer,
                           seller=current_seller)

    user_order.save()

    for product in products:
        prod_list = user_order.prod_list_set.create(product_id=product, pr_amount=products[product])
        prod_list.save()
        del request.session[str(product)]

    new_order = Order.objects.get(pk=user_order.id)
    context = {
        'order': new_order
    }

    return render(request, 'basket/order_success.html', context)

basket/templates/basket/basket.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Корзина</title>

	<link rel="stylesheet" href="{% static 'catalogue/style.css' %}">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>
    <h1 class="headline" style="margin-left: 100px">Корзина</h1>
    <div class="flex">
        <div class="flex column" style="margin-left: 100px; margin-top: 20px; gap: 20px;">
            {% if product_list %}
                {% for product in product_list %}
                    <div class="product flex" id="pr_{{ product.id }}" style="width: 55%">
                        <a href="{% url 'catalogue:product' product.id %}">
                            {% if product.img %}
                            <img src="{{ product.img.url }}" alt="" class="pr_img">
                            {% endif %}
                        </a>
                        <div class="product_info">
                            <p class="pr_price title" id="price{{ product.id }}">{{ product.pr_price }} P</p>
                            <a href="{% url 'catalogue:product' product.id %}">
                                <p class="pr_name subtitle">{{ product.pr_name }}</p>
                            </a>
                            <div class="flex align-items-center space-between change_amount">
                                <button class="add_button" onclick="subtract_item({{ product.id }}, {{ product.pr_price }})">-</button>
                                <p class="subtitle" style="font-weight: 700" id="amount{{ product.id }}">1</p>
                                <button class="add_button" onclick="add_item({{ product.id }}, {{ product.pr_price }})">+</button>
                            </div>
                        </div>
                     </div>
                {% endfor %}
        </div>
        <div>
            <span class="subtitle">Стоимость заказа:</span> <span class="subtitle" id="full_price"></span>
            <br>
            <a href="{% url 'basket:order' %}">
                <button class="primary_button"> Перейти к офомлению </button>
            </a>
        </div>
    </div>
            {% else %}
                <p>Ваша корзина пуста</p>
            {% endif %}

    <script type="text/javascript" src="{% static 'basket/script.js' %}"></script>
    {% if product_items %}
        <script>
            get_items({{ product_items }}, {{ product_prices }});
            show_items();
            calc_full_price();
        </script>
    {% endif %}
</body>
</html>

basket/templates/basket/order.html
{% load static %}
<!DOCTYPE>
<html>
<head>
	<title>Оформление заказа</title>

    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'catalogue/style.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>

    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>

    <h1 class="headline" style="margin-left: 100px">Оформление заказа</h1>

    <div style="margin-left: 100px">
        <h2>Данные покупателя</h2>
        {% if user.is_authenticated %}
            <div>
                <p>Имя: {{ user.first_name }}</p>
                <p>Фамилия: {{ user.last_name }}</p>
                <p>Почта: {{ user.email }}</p>
                <p>Телефон: {{ user.customer.phone }}</p>
                <p>Адрес: {{ user.customer.district }} район, улица {{ user.customer.street }}, дом {{ user.customer.house }},
                корпус {{ user.customer.corp }}, кв.{{ user.customer.flat }}, {{ user.customer.p_index }} </p>
                <a href="{% url 'basket:create_order' %}">
                    <button class="primary_button"> Оформить заказ </button>
                </a>
            </div>
        {% else %}
            <p style="margin-bottom: 10px;">Заполните данные для оформления заказа или <a href="{% url 'login' %}" style="text-decoration: underline">
            авторизуйтесь</a>, чтобы они заполнились автоматически</p>
            <form action="{% url 'basket:create_order' %}" method="POST">
                {% csrf_token %}
                <label for="login">E-mail:<br></label>
			    <input name="login" id="login" type="email" size="20" maxlength="50" required >
                <br>
                <label for="last_name">Фамилия:<br></label>
                <input name="last_name" id="last_name" type="text" size="20" maxlength="30" required onchange = "correct_field('last_name')" >
                <br>
                <label for="first_name">Имя:<br></label>
                <input name="first_name" id="first_name" type="text" size="20" maxlength="30" required  onchange = "correct_field('first_name')">
                <br>
                <label for="phone">Телефон:<br></label>
                <input name="phone" id="phone" type="text" size="20" maxlength="11" >
                <br>
                <h3 style="margin: 0 0 10px;">Адрес</h3>
                <label for="district">Район:<br></label>
                <input name="district" id="district" type="text" size="20" maxlength="30" required  onchange = "correct_field('district')">
                <br>
                <label for="street">Улица:<br></label>
                <input name="street" id="street" type="text" size="20" maxlength="30" required  onchange = "correct_field('street')">
                <br>
                <label for="house">Дом:<br></label>
                <input name="house" id="house" type="number" size="20" required >
                <br>
                <label for="corp">Корпус:<br></label>
                <input name="corp" id="corp" type="number" size="20" >
                <br>
                <label for="flat">Квартира:<br></label>
                <input name="flat" id="flat" type="number" size="20" required >
                <br>
                <label for="p_index">Почтовый индекс:<br></label>
                <input name="p_index" id="p_index" type="number" size="20" required >
                <br>
                <input class="primary_button" style="font-size: 16px" type="submit" value="Оформить заказ" />
            </form>
        {% endif %}
    </div>


<script type="text/javascript" src="{% static 'basket/script.js' %}"></script>
</body>
</html>

basket/templates/basket/order_success.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Заказ оформлен</title>

	<link rel="stylesheet" href="{% static 'catalogue/style.css' %}">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header class="flex space-between caption align-items-center" id="hdr">
		<a href="{% url 'catalogue:index' %}" id="logo" >Сладости и десерты</a>
		<nav class="flex space-between" style="margin-right: 60px;">
			<a href="{% url 'basket:basket' %}" class="navLink">Корзина</a>
			<a href="{% url 'userProfile:userProfile' %}" class="navLink">Личный кабинет</a>
			{% if user.is_authenticated %} <p> {{ user.first_name }} {{ user.last_name }} </p>
            {% else %} <a href="{% url 'login' %}" class="navLink">Войти</a>
            {% endif %}
		</nav>
	</header>

    <h1 class="headline" style="margin-left: 100px">Заказ оформлен</h1>

    <div style="margin-left: 100px">
        <p>Номер заказа: {{ order.id }}</p>
        {% language 'ru' %}
            <p>Дата оформления {{ order.cr_date }}</p>
        {% endlanguage %}
        <p>Покупатель: {{ order.customer.user.first_name }} {{ order.customer.user.last_name }}</p>
        <p>Продавец: {{ order.seller.user.first_name }} {{ order.seller.user.last_name }}</p>
        <p>Стоимость: {{ order.full_pr }} P</p>
        <p>Состав заказа: </p>
        {% for pr_list in order.prod_list_set.all %}
            <span>{{ pr_list.product }} {{ pr_list.pr_amount }}шт. </span>
        {% endfor %}
    </div>


</body>
</html>